# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\"\x18\n\x08HelloReq\x12\x0c\n\x04Name\x18\x01 \x01(\t\"\x19\n\tHelloResp\x12\x0c\n\x04Resp\x18\x01 \x01(\t2.\n\x07Greeter\x12#\n\x08SayHello\x12\t.HelloReq\x1a\n.HelloResp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HELLOREQ']._serialized_start=15
  _globals['_HELLOREQ']._serialized_end=39
  _globals['_HELLORESP']._serialized_start=41
  _globals['_HELLORESP']._serialized_end=66
  _globals['_GREETER']._serialized_start=68
  _globals['_GREETER']._serialized_end=114
# @@protoc_insertion_point(module_scope)
